version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ./src/generateCaptionHTML.py
          name: generate HTML
      - run :
          command : tar -czvf build/dofin.tgz webcontent/
          name : build Web Site
      - run :
          command : tar -tzvf build/dofin.tgz & pwd & uname -a & id
          name : metaData Info

workflows:
  main:
    jobs:
      - build
